

export const pathScripts = [
    "https://cdn.tailwindcss.com",
  ];

export const pathStyles = [
  ];

const tailwindColors = [
    { value: "black" },
    { value: "white" },
    { value: "slate-50" },
    { value: "slate-100" },
    { value: "slate-200" },
    { value: "slate-300" },
    { value: "slate-400" },
    { value: "slate-500" },
    { value: "slate-600" },
    { value: "slate-700" },
    { value: "slate-800" },
    { value: "slate-900" },
    { value: "slate-950" },
    { value: "gray-50" },
    { value: "gray-100" },
    { value: "gray-200" },
    { value: "gray-300" },
    { value: "gray-400" },
    { value: "gray-500" },
    { value: "gray-600" },
    { value: "gray-700" },
    { value: "gray-800" },
    { value: "gray-900" },
    { value: "gray-950" },
    { value: "zinc-50" },
    { value: "zinc-100" },
    { value: "zinc-200" },
    { value: "zinc-300" },
    { value: "zinc-400" },
    { value: "zinc-500" },
    { value: "zinc-600" },
    { value: "zinc-700" },
    { value: "zinc-800" },
    { value: "zinc-900" },
    { value: "zinc-950" },
    { value: "neutral-50" },
    { value: "neutral-100" },
    { value: "neutral-200" },
    { value: "neutral-300" },
    { value: "neutral-400" },
    { value: "neutral-500" },
    { value: "neutral-600" },
    { value: "neutral-700" },
    { value: "neutral-800" },
    { value: "neutral-900" },
    { value: "neutral-950" },
    { value: "stone-50" },
    { value: "stone-100" },
    { value: "stone-200" },
    { value: "stone-300" },
    { value: "stone-400" },
    { value: "stone-500" },
    { value: "stone-600" },
    { value: "stone-700" },
    { value: "stone-800" },
    { value: "stone-900" },
    { value: "stone-950" },
    { value: "red-50" },
    { value: "red-100" },
    { value: "red-200" },
    { value: "red-300" },
    { value: "red-400" },
    { value: "red-500" },
    { value: "red-600" },
    { value: "red-700" },
    { value: "red-800" },
    { value: "red-900" },
    { value: "red-950" },
    { value: "orange-50" },
    { value: "orange-100" },
    { value: "orange-200" },
    { value: "orange-300" },
    { value: "orange-400" },
    { value: "orange-500" },
    { value: "orange-600" },
    { value: "orange-700" },
    { value: "orange-800" },
    { value: "orange-900" },
    { value: "orange-950" },
    { value: "amber-50" },
    { value: "amber-100" },
    { value: "amber-200" },
    { value: "amber-300" },
    { value: "amber-400" },
    { value: "amber-500" },
    { value: "amber-600" },
    { value: "amber-700" },
    { value: "amber-800" },
    { value: "amber-900" },
    { value: "amber-950" },
    { value: "yellow-50" },
    { value: "yellow-100" },
    { value: "yellow-200" },
    { value: "yellow-300" },
    { value: "yellow-400" },
    { value: "yellow-500" },
    { value: "yellow-600" },
    { value: "yellow-700" },
    { value: "yellow-800" },
    { value: "yellow-900" },
    { value: "yellow-950" },
    { value: "lime-50" },
    { value: "lime-100" },
    { value: "lime-200" },
    { value: "lime-300" },
    { value: "lime-400" },
    { value: "lime-500" },
    { value: "lime-600" },
    { value: "lime-700" },
    { value: "lime-800" },
    { value: "lime-900" },
    { value: "lime-950" },
    { value: "green-50" },
    { value: "green-100" },
    { value: "green-200" },
    { value: "green-300" },
    { value: "green-400" },
    { value: "green-500" },
    { value: "green-600" },
    { value: "green-700" },
    { value: "green-800" },
    { value: "green-900" },
    { value: "green-950" },
    { value: "emerald-50" },
    { value: "emerald-100" },
    { value: "emerald-200" },
    { value: "emerald-300" },
    { value: "emerald-400" },
    { value: "emerald-500" },
    { value: "emerald-600" },
    { value: "emerald-700" },
    { value: "emerald-800" },
    { value: "emerald-900" },
    { value: "emerald-950" },
    { value: "teal-50" },
    { value: "teal-100" },
    { value: "teal-200" },
    { value: "teal-300" },
    { value: "teal-400" },
    { value: "teal-500" },
    { value: "teal-600" },
    { value: "teal-700" },
    { value: "teal-800" },
    { value: "teal-900" },
    { value: "teal-950" },
    { value: "cyan-50" },
    { value: "cyan-100" },
    { value: "cyan-200" },
    { value: "cyan-300" },
    { value: "cyan-400" },
    { value: "cyan-500" },
    { value: "cyan-600" },
    { value: "cyan-700" },
    { value: "cyan-800" },
    { value: "cyan-900" },
    { value: "cyan-950" },
    { value: "sky-50" },
    { value: "sky-100" },
    { value: "sky-200" },
    { value: "sky-300" },
    { value: "sky-400" },
    { value: "sky-500" },
    { value: "sky-600" },
    { value: "sky-700" },
    { value: "sky-800" },
    { value: "sky-900" },
    { value: "sky-950" },
    { value: "blue-50" },
    { value: "blue-100" },
    { value: "blue-200" },
    { value: "blue-300" },
    { value: "blue-400" },
    { value: "blue-500" },
    { value: "blue-600" },
    { value: "blue-700" },
    { value: "blue-800" },
    { value: "blue-900" },
    { value: "blue-950" },
    { value: "indigo-50" },
    { value: "indigo-100" },
    { value: "indigo-200" },
    { value: "indigo-300" },
    { value: "indigo-400" },
    { value: "indigo-500" },
    { value: "indigo-600" },
    { value: "indigo-700" },
    { value: "indigo-800" },
    { value: "indigo-900" },
    { value: "indigo-950" },
    { value: "violet-50" },
    { value: "violet-100" },
    { value: "violet-200" },
    { value: "violet-300" },
    { value: "violet-400" },
    { value: "violet-500" },
    { value: "violet-600" },
    { value: "violet-700" },
    { value: "violet-800" },
    { value: "violet-900" },
    { value: "violet-950" },
    { value: "purple-50" },
    { value: "purple-100" },
    { value: "purple-200" },
    { value: "purple-300" },
    { value: "purple-400" },
    { value: "purple-500" },
    { value: "purple-600" },
    { value: "purple-700" },
    { value: "purple-800" },
    { value: "purple-900" },
    { value: "purple-950" },
    { value: "fuchsia-50" },
    { value: "fuchsia-100" },
    { value: "fuchsia-200" },
    { value: "fuchsia-300" },
    { value: "fuchsia-400" },
    { value: "fuchsia-500" },
    { value: "fuchsia-600" },
    { value: "fuchsia-700" },
    { value: "fuchsia-800" },
    { value: "fuchsia-900" },
    { value: "fuchsia-950" },
    { value: "pink-50" },
    { value: "pink-100" },
    { value: "pink-200" },
    { value: "pink-300" },
    { value: "pink-400" },
    { value: "pink-500" },
    { value: "pink-600" },
    { value: "pink-700" },
    { value: "pink-800" },
    { value: "pink-900" },
    { value: "pink-950" },
    { value: "rose-50" },
    { value: "rose-100" },
    { value: "rose-200" },
    { value: "rose-300" },
    { value: "rose-400" },
    { value: "rose-500" },
    { value: "rose-600" },
    { value: "rose-700" },
    { value: "rose-800" },
    { value: "rose-900" },
    { value: "rose-950" },
  ];

const tailwindShadows = [
    { value: "sm" }, // shadow-sm
    { value: "DEFAULT" }, // shadow
    { value: "md" }, // shadow-md
    { value: "lg" }, // shadow-lg
    { value: "xl" }, // shadow-xl
    { value: "2xl" }, // shadow-2xl
    { value: "inner" }, // shadow-inner
    { value: "none" }, // shadow-none
    { value: "outline" }, // shadow-outline
    { value: "default" }, // shadow-default
  ];

const tailwindBorderRadius = [
    { value: "none" }, // border-none
    { value: "sm" }, // rounded-sm
    { value: "DEFAULT" }, // rounded
    { value: "md" }, // rounded-md
    { value: "lg" }, // rounded-lg
    { value: "xl" }, // rounded-xl
    { value: "2xl" }, // rounded-2xl
    { value: "3xl" }, // rounded-3xl
    { value: "full" }, // rounded-full
  ];

export const styleManagerBaseTailwindCss = {
    sectors: [
      {
        name: "General",
        buildProps: ["float", "display", "position"],
        properties: [
          {
            name: "Alignment",
            property: "float",
            type: "radio",
            className: "float-{value}",
          },
          {
            name: "Display",
            property: "display",
            type: "select",
            className: "{value}",
          },
          {
            property: "position",
            type: "select",
            default: "static",
            className: "{value}",
          },
        ],
      },
      {
        name: "Dimension",
        open: false,
        buildProps: ["width", "height", "margin", "padding"],
        properties: [
          {
            id: "flex-width",
            type: "integer",
            name: "Width",
            units: [""],
            property: "width",
            className: "w-{value}",
          },
          {
            id: "flex-height",
            type: "integer",
            name: "height",
            units: [""],
            property: "height",
            className: "h-{value}",
          },
          {
            property: "margin",
            properties: [
              {
                name: "Top",
                property: "mt",
                type: "integer",
                className: "mt-{value}",
              },
              {
                name: "Right",
                property: "mr",
                type: "integer",
                className: "mr-{value}",
              },
              {
                name: "Bottom",
                property: "mb",
                type: "integer",
                className: "mb-{value}",
              },
              {
                name: "Left",
                property: "ml",
                type: "integer",
                className: "ml-{value}",
              },
            ],
          },
          {
            property: "padding",
            properties: [
              {
                name: "Top",
                property: "pt",
                type: "integer",
                className: "pt-{value}",
              },
              {
                name: "Right",
                property: "pr",
                type: "integer",
                className: "pr-{value}",
              },
              {
                name: "Bottom",
                property: "pb",
                type: "integer",
                className: "pb-{value}",
              },
              {
                name: "Left",
                property: "pl",
                type: "integer",
                className: "pl-{value}",
              },
            ],
          },
        ],
      },
      {
        name: "Typography",
        open: false,
        buildProps: [
          "font-weight",
          "color",
          "text-align",
          "text-decoration",
        ],
        properties: [
          {
            name: "Weight",
            property: "font-weight",
            className: "font-{value}",
          },
          {
            name: "Font Color",
            type: "select",
            property: "color",
            className: "text-{value}",
            list: tailwindColors,
          },
          {
            property: "text-align",
            type: "radio",
            default: "text-left",
            className: "text-{value}",
          },
          {
            property: "text-decoration",
            type: "select",
            defaults: "no-underline",
            className: "{value}",
            list: [
              { value: "underline" },
              { value: "line-through" },
              { value: "no-underline" },
            ],
          },
        ],
      },
      {
        name: "Decorations",
        open: false,
        buildProps: [
          "opacity",
          "border-radius",
          "box-shadow",
          "background",
        ],
        properties: [
          {
            type: "slider",
            property: "opacity",
            default: 1,
            step: 0.01,
            max: 1,
            min: 0,
            className: "opacity-{value}",
          },
          {
            property: "border-radius",
            properties: [
              {
                name: "Top Left",
                property: "rounded-tl",
                className: "rounded-tl-{value}",
                type: "select",
                list: tailwindBorderRadius,
              },
              {
                name: "Top Right",
                property: "rounded-tr",
                className: "rounded-tr-{value}",
                type: "select",
                list: tailwindBorderRadius,
              },
              {
                name: "Bottom Left",
                property: "rounded-bl",
                className: "rounded-bl-{value}",
                type: "select",
                list: tailwindBorderRadius,
              },
              {
                name: "Bottom Right",
                property: "rounded-br",
                className: "rounded-br-{value}",
                type: "select",
                list: tailwindBorderRadius,
              },
            ],
          },
          {
            property: "box-shadow",
            properties: [
              {
                name: "Shadow",
                property: "shadow",
                className: "shadow-{value}",
                type: "select",
                list: tailwindShadows,
              },
            ],
          },
          {
            id: "background",
            property: "background",
            type: "select",
            className: "bg-{value}",
            list: tailwindColors,
          },
        ],
      },
      {
        name: "Flex",
        open: false,
        properties: [
          {
            name: "Display",
            property: "display",
            type: "select",
            default: "block",
            className: "{value}",
            list: [
              {
                value: "block",
                name: "Block",
                className: "block",
              },
              {
                value: "flex",
                name: "Flex",
                className: "flex",
              },
            ],
          },
          {
            name: "Flex Direction",
            property: "flex-directions",
            type: "select",
            default: "flex-row",
            className: "{value}",
            list: [
              {
                value: "flex-row",
                name: "Row",
                className: "flex-row",
              },
              {
                value: "flex-col",
                name: "Column",
                className: "flex-col",
              },
            ],
          },
          {
            name: "Justify Content",
            property: "justify-contents",
            type: "select",
            default: "justify-start",
            className: "{value}",
            list: [
              {
                value: "justify-start",
                name: "Start",
                className: "justify-start",
              },
              {
                value: "justify-end",
                name: "End",
                className: "justify-end",
              },
              {
                value: "justify-center",
                name: "Center",
                className: "justify-center",
              },
              {
                value: "justify-between",
                name: "Space Between",
                className: "justify-between",
              },
              {
                value: "justify-around",
                name: "Space Around",
                className: "justify-around",
              },
            ],
          },
          {
            name: "Align Items",
            type: "select",
            property: "align-items",
            default: "items-start",
            className: "{value}",
            list: [
              {
                value: "items-start",
                name: "Start",
                className: "items-start",
              },
              {
                value: "items-end",
                name: "End",
                className: "items-end",
              },
              {
                value: "items-center",
                name: "Center",
                className: "items-center",
              },
              {
                value: "items-stretch",
                name: "Stretch",
                className: "items-stretch",
              },
            ],
          },
        ],
      },
    ],
  };
